import React from 'react'
import Navbar from './Navbar'
import { carsousel1,carsousel2,carsousel3,shop,bg,art} from './resources'
import Subnav from './Subnav'
import Contact from './Contact'
import Footer from './Footer'
import { Offline, Online } from 'react-detect-offline'
import Lazy from './Lazy'

function Home() {
  return (
    <>
    {/* <Offline>
    <div className='off'>
        <div className='container offline'>
            <h1 className=''>OOPS..</h1>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-wifi-off" viewBox="0 0 16 16">
  <path d="M10.706 3.294A12.545 12.545 0 0 0 8 3C5.259 3 2.723 3.882.663 5.379a.485.485 0 0 0-.048.736.518.518 0 0 0 .668.05A11.448 11.448 0 0 1 8 4c.63 0 1.249.05 1.852.148l.854-.854zM8 6c-1.905 0-3.68.56-5.166 1.526a.48.48 0 0 0-.063.745.525.525 0 0 0 .652.065 8.448 8.448 0 0 1 3.51-1.27L8 6zm2.596 1.404.785-.785c.63.24 1.227.545 1.785.907a.482.482 0 0 1 .063.745.525.525 0 0 1-.652.065 8.462 8.462 0 0 0-1.98-.932zM8 10l.933-.933a6.455 6.455 0 0 1 2.013.637c.285.145.326.524.1.75l-.015.015a.532.532 0 0 1-.611.09A5.478 5.478 0 0 0 8 10zm4.905-4.905.747-.747c.59.3 1.153.645 1.685 1.03a.485.485 0 0 1 .047.737.518.518 0 0 1-.668.05 11.493 11.493 0 0 0-1.811-1.07zM9.02 11.78c.238.14.236.464.04.66l-.707.706a.5.5 0 0 1-.707 0l-.707-.707c-.195-.195-.197-.518.04-.66A1.99 1.99 0 0 1 8 11.5c.374 0 .723.102 1.021.28zm4.355-9.905a.53.53 0 0 1 .75.75l-10.75 10.75a.53.53 0 0 1-.75-.75l10.75-10.75z"/>
</svg>
            <h5>Come Back when You Are Conacted</h5>
        </div>
    </div>
    </Offline> */}
{/* <Online> */}
<Navbar/>
    <div id="carouselExampleIndicators" className="carousel slide carousel-navbar" data-ride="carousel">
  <ol className="carousel-indicators">
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to={0} className="active" />
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to={1} />
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to={2} />
  </ol>
  <div className="carousel-inner">
    <div className="carousel-item active">
      <img src={carsousel1} className="d-block w-100" alt="..." />
    </div>
    <div className="carousel-item">
      <img src={carsousel2} className="d-block w-100" alt="..." />
    </div>
    <div className="carousel-item">
      <img src={carsousel3} className="d-block w-100" alt="..." />
    </div>
  </div>
  <a className="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
    <span className="carousel-control-prev-icon" aria-hidden="true" />
    <span className="sr-only">Previous</span>
  </a>
  <a className="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
    <span className="carousel-control-next-icon" aria-hidden="true" />
    <span className="sr-only">Next</span>
  </a>
</div>
<Subnav></Subnav>
<div className='part2'><h3 className='description'>Finding the art in neural networks. Our mission is to revolutionise the art world and to become the exclusive provider of art generated by artificial neural networks – paintings which are both unique and exclusive – whereas some try to replicate human behaviour – other take paths of their own. We just started and are looking for other ai artists to collaborate with. If you are one of them shoot us an email.</h3></div>

<div className='what-art-container'>
    <img className='img-fluid' src={bg} ></img>
    <div className='what-art'>
        <h2>What to offer</h2>
        <p className='text-center'>
        Finding the art in neural networks. Our mission is to revolutionise the art world and to become the exclusive provider of art generated by artificial neural networks – paintings which are both unique and exclusive – whereas some try to replicate human behaviour – other take paths of their own. We just started and are looking for other ai artists to collaborate with. If you are one of them shoot us an email.
        </p>
    </div>
    <button className='btn btn-small'>Follow us on instgram</button>
</div>
<p className='text-center bab'>We have active cummunity on instegram ,Make Sure to follow</p>

<Lazy></Lazy>

<div className='contact' id='contact'>
<div className='my-5'>
    <h3>Contact Us : </h3>
    <p></p>
    <div className='container contact_ele'>
        <Contact DBref='Inbox' />
    </div>
</div>
</div>

<Lazy></Lazy>
<Footer/>
{/* </Online> */}

    </>
  )
}

export default Home
